### ISSUE TITLE
undefined: context

### ISSUE THREAD

**Issue by sambengtson** [fuzxxl/nfc#11]
I installed the library using go get

> go get github.com/fuzxxl/nfc

I'm receiving a build error that would indicate that I possibly installed the library incorrectly.

> ../github.com/fuzxxl/nfc/2.0/nfc/nfc.go:206: undefined: context

I tried downloading the root project directly into my GOPATH but am still experiencing the same behavior.  Can you advise?  I'm sure it's something dumb that I'm overlooking.

**Comment by Abhishek-Nagarkoti** [comment]
Which Go version are you using. I don't think that if your go version is greater that 1.6 than this should be issue

**Comment by sambengtson** [comment]
Sorry, I should have specified.  Go1.8

**Comment by Abhishek-Nagarkoti** [comment]
ohh that was stupid of me, this is not that issue. Let me see

**Comment by hsanjuan** [comment]
`go get github.com/fuzxxl/nfc/2.0/nfc` works for me...

**Comment by sambengtson** [comment]
@hsanjuan You don't see anything like this?

> sam@sam-VirtualBox:~/Go/src/github.com$ go get github.com/fuzxxl/nfc/2.0/nfc
> # github.com/fuzxxl/nfc/2.0/nfc
> ../../../.gvm/pkgsets/go1.8/global/src/github.com/fuzxxl/nfc/2.0/nfc/nfc.go:206: undefined: context

**Comment by hsanjuan** [comment]
Ah. This happens to me when trying to compile with CGO_ENABLED=0

Try CGO_ENABLED=1. Since this library is a C binding you probably need to use CGO.

**Comment by sambengtson** [comment]
@hsanjuan There we go!  Thanks!
