### ISSUE TITLE
Device.InitiatorSelectPassiveTarget panic when InfiniteSelect == false and no tag was found

### ISSUE THREAD

**Issue by wincss** [fuzxxl/nfc#9]
Problem
--

When InfiniteSelect == false, nfc_initiator_select_passive_target return 0 when no tag was found, but Device.InitiatorSelectPassiveTarget always calls unmarshallTarget.

Example in https://github.com/nfc-tools/libnfc/blob/master/utils/nfc-mfclassic.c

      if (nfc_initiator_select_passive_target(pnd, nmMifare, NULL, 0, &nt) <= 0) {
        printf("Error: no tag was found\n");
        nfc_close(pnd);
        nfc_exit(context);
        exit(EXIT_FAILURE);
      }

This code use <= 0 for error checking.

How to reproduce
--

    func main() {
        dev, _ := nfc.Open("")
        defer dev.Close()
        dev.InitiatorInit()
        dev.SetPropertyBool(nfc.InfiniteSelect, false)
        dev.SetPropertyBool(nfc.AutoISO14443_4, false)
        fmt.Printf("NFC reader: %s opened\n", dev)
        dev.InitiatorSelectPassiveTarget(nmMifare, nil) // panic when no tag was present
    }

 Affected version
--
all version include latest

**Comment by fuzxxl** [comment]
If you make a patch, I'll include it. Otherwise, you have to wait until I get around doing this.

**Comment by wincss** [comment]
@fuzxxl OK, I'll submit a pull request later.

Should I fix it just in lastest version(2.0), or in all versions?

**Comment by fuzxxl** [comment]
Just fix 2.0 and dev. The other paths aren't maintained. Don't forget to update CHANGES as well and enter yourself as an author into the file you update together with an updated copyright year.
